In [1]:
import geopandas as gpd
mask = gpd.read_file('../data/GIS/SkagitBoundary.json')
mask

,OBJECTID,AREA,PERIMETER,SKAGIT_,SKAGIT_ID,GRID_CODE,Shape_Leng,Shape_Area,geometry
0,1,8.060220e+09,948300.0,2,1,1,948300.0,8.060220e+09,"POLYGON ((-120.81726 49.26101, -120.8152 49.26..."

In [2]:
mask.explore()

In [11]:
gf = gpd.read_file('../data/GIS/SkagitSubBasin_HUC8.geojson')
gf = gf[gf.Name.isin(['Upper Skagit', 'Lower Skagit', 'Sauk'])]
gf

,OBJECTID,AreaAcres,AreaSqKm,States,HUC8,Name,TNMID,LoadDate,GNIS_ID,GlobalID,geometry
29,30,1286652.51,5206.90,"CN,WA",17110005,Upper Skagit,{BEF5D139-B56E-43A5-A9A7-EB27E6F0B6A9},"Fri, 18 Jan 2013 13:55:14 GMT",None,4475071d-73f2-4677-8bc6-9be98fc3ac6a,"POLYGON ((-120.99842 49.31152, -120.99836 49.3..."
65,66,468724.20,1896.86,WA,17110006,Sauk,{DB785059-BDAB-402A-B6B6-2575A82A8381},"Fri, 18 Jan 2013 13:55:14 GMT",None,d2b15bce-ed33-4152-b761-60a7add8fab7,"POLYGON ((-121.60702 48.4814, -121.60401 48.48..."
66,67,289711.45,1172.42,WA,17110007,Lower Skagit,{BB64475B-E0E8-4D0F-8DC4-3C9DA047A02B},"Fri, 18 Jan 2013 13:55:14 GMT",None,05bfeac3-1f44-4fe7-8725-20f9ece30909,"MULTIPOLYGON (((-121.81821 48.61408, -121.8173..."

In [40]:
m = gf.explore(column='Name', cmap='tab10')
mask.explore(m=m,
          style_kwds={
        'fillOpacity': 0,  # Set fill opacity to 0 to remove fill
        'color': 'blue',   # Set outline color (e.g., blue)
        'weight': 3        # Set outline weight (e.g., 3 pixels)
    }
)

In [37]:
mask

,OBJECTID,AREA,PERIMETER,SKAGIT_,SKAGIT_ID,GRID_CODE,Shape_Leng,Shape_Area,geometry
0,1,8.060220e+09,948300.0,2,1,1,948300.0,8.060220e+09,"POLYGON ((-120.81726 49.26101, -120.8152 49.26..."